name: self-hosted-runner-build-push

on: push

jobs:
  multi:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build
        run: |
          cd c-hello-world
          docker build -t ${{ secrets.DOCKER_USERNAME }}/c-hello-world .
      -
         name: Push
         run: docker push ${{ secrets.DOCKER_USERNAME }}/c-hello-world:latest
